### ISSUE TITLE
Add task groupings

### ISSUE THREAD

**Issue by cnsidero** [sayerhs/cpl#8]
To facilitate workflows that require collaboration between case directories, a mechanism to group tasks based on the case directory should be added.

A suggested solution would be to add a new task called `task_group` where the case directory is used by all sub-tasks. E.g. yaml

```
tasks:
   - task_group:
        case_dir: <coarse mesh case dir>
        - clean_case:
             remove_zero: no
             remove_mesh: no
        - run_command:
            cmd_name: simpleSolver
   - task_group:
        case_dir: <fine mesh case dir>
        - run_command:
            cmd_name: mapFields
            cmd_args: "<coarse mesh case dir> -consistent -sourceTime latestTime"
        - run_command:
            cmd_name: decomposePar
            cmd_args: "-force"
        - run_command:
            cmd_name: simpleSolver
            parallel: True
```
